### ISSUE TITLE
add .nvmrc

### ISSUE THREAD

**Issue by wzalazar** [firesquadio/nodejs-api-sdk#1]
Add `.nvmrc` with the goal to track the nodejs version

- Check the version that is already used in CI and set the version in the `.nvrm`
- Update the CI file for getting the version from `.nvmrc`
- Review if the  lambda is using the same version

Example:

```
- name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

- name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
```
